Name: Jill_Smith_example's assignment
Date/Time: 2023-03-30 20:45:21.414802

============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.3, pluggy-1.0.0 -- C:\Users\evan\AppData\Local\Programs\Python\Python310\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\evan\Desktop\Autograder\Autograder
collecting ... collected 3 items

To_Grade/_test.py::test_module_output PASSED                             [ 33%]
To_Grade/_test.py::test_function_output FAILED                           [ 66%]
To_Grade/_test.py::test_function_return PASSED                           [100%]

================================== FAILURES ===================================
____________________________ test_function_output _____________________________

    def test_function_output():
    
      #test that the function definition is present in module
      assert hasattr(module, 'print_fun'), "'print_fun' function definition not found"
    
    
      #test printed output of a function
    
      #expected_output = os.path.join(dir_path, expected_output_file) #used to store the output to check against
      expected_output = "Hello World" #used with short outputs
      #NOTE: expected output should include any newline characters \n
    
    
      captured_output = io.StringIO()
      sys.stdout = captured_output
    
      module.print_fun() #change to function name
    
      sys.stdout = sys.__stdout__
    #ignore above ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #assertions===========================================================================================================================================
>     assert captured_output.getvalue().strip() == expected_output.strip(), f"Expected {expected_output}, but got {captured_output.getvalue()}"
E     AssertionError: Expected Hello World, but got Hello d
E       
E     assert 'Hello d' == 'Hello World'
E       - Hello World
E       ?       ----
E       + Hello d

To_Grade\_test.py:52: AssertionError
=========================== short test summary info ===========================
FAILED To_Grade/_test.py::test_function_output - AssertionError: Expected Hel...
========================= 1 failed, 2 passed in 0.11s =========================
